-- 1 UTILIZAR A BASE DE DADOS ABD_03361_EdsonLuiz
 USE ABD_03361_EdsonLuiz;
 
-- 2 CRIAR A TABELA DE CLIENTES_BANCO_ITAU
-- CAMPOS:
-- ID_CLIENTE (INT AUTO_INCREMENT, PRIMARY KEY)
-- NOME_CLIENTE (VARCHAR 100)
-- CPF (VARCHAR 11)
  -- Script
 CREATE TABLE CLIENTES_BANCO_ITAU (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(100),
    CPF VARCHAR(11)
);
 
-- 3 CRIAR A TABELA DE CONTAS
-- CAMPOS:
-- ID_CONTA (INT AUTO_INCREMENT, PRIMARY KEY)
-- ID_CLIENTE (INT, FK)
-- SALDO (DECIMAL 10,2)
-- TIPO_CONTA (VARCHAR 20)
-- Script 
CREATE TABLE CONTAS (
    ID_CONTA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT,
    SALDO DECIMAL(10,2),
    TIPO_CONTA VARCHAR(20),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES_BANCO_ITAU(ID_CLIENTE)
);

-- 4 POPULAR A TABELA CLIENTES COM 5 CLIENTES SEM DEFINIR AS COLUNAS
-- Script
INSERT INTO CLIENTES_BANCO_ITAU
VALUES 
(NULL, 'João Silva', '12345678901'),
(NULL, 'Pedro Lima', '23456789012'),
(NULL, 'Maria Souza', '34567890123'),
(NULL, 'Ana Costa', '45678901234'),
(NULL, 'Carlos Mendes', '56789012345');

-- 5 POPULAR A TABELA CONTAS COM 5 CONTAS
 -- Script
 INSERT INTO CONTAS (ID_CLIENTE, SALDO, TIPO_CONTA)
VALUES
(1, 1000.00, 'Corrente'),
(2, 500.00, 'Poupança'),
(3, 1500.00, 'Corrente'),
(4, 2000.00, 'Poupança'),
(5, 300.00, 'Corrente');

-- 6 EXERCÍCIO DE TRANSACÇÃO COM RELAÇÃO ENTRE CLIENTES E CONTAS
-- Script
START TRANSACTION;

-- Passo 2: Diminuir saldo de João Silva
UPDATE CONTAS
SET SALDO = SALDO - 600
WHERE ID_CLIENTE = (SELECT ID_CLIENTE FROM CLIENTES_BANCO_ITAU WHERE NOME_CLIENTE = 'João Silva');

-- Passo 3: Aumentar saldo de Pedro Lima
UPDATE CONTAS
SET SALDO = SALDO + 600
WHERE ID_CLIENTE = (SELECT ID_CLIENTE FROM CLIENTES_BANCO_ITAU WHERE NOME_CLIENTE = 'Pedro Lima');

-- Passo 4: Verificar se saldo de João ficou negativo
-- Se sim, fazer ROLLBACK, senão COMMIT
-- (Simulação com variável temporária)
SET @saldo_joao := (SELECT SALDO FROM CONTAS WHERE ID_CLIENTE = (SELECT ID_CLIENTE FROM CLIENTES_BANCO_ITAU WHERE NOME_CLIENTE = 'João Silva'));

IF @saldo_joao < 0 THEN
    ROLLBACK;
ELSE
    COMMIT;
END IF;

SELECT SALDO FROM CONTAS WHERE ID_CLIENTE = 1;


Select * from CLIENTES_BANCO_ITAU
Select * from CONTAS;


SELECT 
    c.ID_CONTA,
    cli.NOME_CLIENTE,
    cli.CPF,
    c.SALDO,
    c.TIPO_CONTA
FROM CONTAS c
JOIN CLIENTES_BANCO_ITAU cli ON c.ID_CLIENTE = cli.ID_CLIENTE;


-- SITUAÇÃO: QUEREMOS TRANSFERIR 600 REAIS DE JOÃO SILVA PARA PEDRO LIMA
-- PASSO 1: INICIAR A TRANSACAO (BEGIN)
-- PASSO 2: DIMINUIR SALDO DE JOÃO SILVA
-- PASSO 3: AUMENTAR SALDO DE PEDRO LIMA
-- PASSO 4: SE SALDO DE JOÃO FICAR NEGATIVO, FAZER ROLLBACK, SENÃO COMMIT


